Develop
derrick1451/ruby-capstone pull request #56
Opened 2023-08-24 17:58 UTC by Benawi

## [Implemented Features](https://github.com/derrick1451/ruby-capstone/issues/37)
### General requirements
- Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config).
- Make sure that you used the correct [Gitflow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md).
- Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md).
### Ruby requirements
- Follow our list of [best practices for Ruby](https://github.com/microverseinc/curriculum-ruby/blob/main/articles/ruby_best_practices.md).
### Project requirements
- [x] All methods visible in the [diagram](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/images/catalog_of_my_things.png) should be implemented
- [x] Set up associations between classes and objects.
- [x] Store data in files.
- [x] Build interactive console apps

2023-08-24 19:38 UTC, danmainah requested changes
Hi @Benawi , @kayjeee and @derrick1451 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Esnured all the options in the UI are working correctly
✔️  Ensured data is stored correctly after the user exits the app.
✔️  All the test added are passing.


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-08-24 19:38 UTC, danmainah commented on spec/author_spec.rb
> +  end
- [ ] @Team great work adding tests for the author class however you forgot to add tests for these methods: to_s,  to_json, and self.from_json
![image](https://github.com/derrick1451/ruby-capstone/assets/61408860/1a9abad9-fd4e-4cb6-aa91-37c160aaa37b)

2023-08-24 19:38 UTC, danmainah commented on spec/genre_spec.rb
> +  end
- [ ] @Team great work adding tests for the genre class however you forgot to add tests for these methods: to_s,to_json, and self.from_json

2023-08-24 19:38 UTC, danmainah commented on spec/genre_spec.rb
> +  end
- [ ] @Team I noted you have not added tests for the item class kindly consider adding tests for this class

2023-08-24 19:38 UTC, danmainah commented on spec/book_spec.rb
> +  end
- [ ] @Team great work adding tests for the book class however you forgot to add tests for these methods: to_s,to_json, and self.from_json

2023-08-24 19:38 UTC, danmainah commented on spec/album_spec.rb
> +  end
- [ ] @Team great work adding tests for the music album class however you forgot to add tests for these methods: to_s,to_json, and self.from_json

2023-08-24 19:38 UTC, danmainah commented on spec/game_spec.rb
> +  end
- [ ] @Team great work adding tests for the game class however you forgot to add tests for these methods: to_s,to_json, and self.from_json

2023-08-24 19:38 UTC, danmainah commented on sql/schema.sql
> +  CONSTRAINT kf_genres FOREIGN KEY(genre_id) REFERENCES genres(id) ON DELETE CASCADE
- [ ] @Team you forgot to add references for the game_id and author_id ,kindly add their references.

2023-08-25 09:23 UTC, Benawi commented
## Changes ♻
- [x] A new video recorded [👁 Walkthrough](https://drive.google.com/file/d/1p-FD-SK1DSDMRLGiTpuNjYJOdMWLcB-T/view?usp=sharing)

2023-08-25 11:05 UTC, OyePriscilla requested changes
Hi @Benawi, @kayjeee and @derrick1451 👏 👏 👏 👏, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Engaging presentation within time frame ✔️ 
Implemented tests for `to.s and to_json` methods ✔️ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 11:16 UTC, Benawi commented
## Changes ♻
- [x] All the repeated tables (Items) removed from [sql/schema.sql](https://github.com/derrick1451/ruby-capstone/pull/56/files/04031d00043c640e31713e814e8c87c44acd5428#diff-c4c0021442fe03b6f1aebb62fed2fe167c0016862c2f74d2689f141a010ea9ad)

2023-08-25 11:57 UTC, KanzaTahreem approved these changes
# Approved 🙌

Hi @team

Good job implementing the suggested changes 💪 **_Your project is COMPLETE! There is nothing else to say other than... it's time to merge it! 🚀 Congratulations!_**

<img src="https://media.tenor.com/xDHCe07zrocAAAAC/congrats-minions.gif"/>

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ Repeated tables are removed
-  ✅ Your README looks good
-  ✅ Linters are working properly

## Optional suggestions ❕
N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 11:59 UTC, merged